import { useMutation, useQuery } from "convex/react";
import { api } from "../convex/_generated/api";

type Row = { _id:string; teamDisplayName:string; route:string; recommendation:string; ownerId?:string; status?:string; deliveryState:string; updatedAt:string };
const label = (route:string) => route === "emerging" ? "Emerging" : route === "direct" ? "Direct request" : route === "both" ? "Direct + pressure" : "Pressure";
const tone = (route:string) => route === "emerging" ? "watch" : route === "direct" || route === "both" ? "urgent" : "ready";
export function App({offline=false}:{offline?:boolean}) {
 const rows = useQuery(api.reviews.listCandidates) as Row[] | undefined;
 const decide = useMutation(api.reviews.recordDecision);
 if (offline) return <main className="app"><header><span className="mark">◻</span><p className="eyebrow">CONVEX · GTM SIGNAL REVIEW</p><h1>Connect a local Convex URL<br/>to open the decision queue.</h1><p className="sub">This visual layer reads synthetic data only.</p></header></main>;
 const open = rows?.filter(r => (r.status ?? "open") === "open") ?? [];
 return <main className="app"><header className="hero"><div className="top"><span className="mark">◻</span><span>GTM SIGNAL REVIEW <i>·</i> SYNTHETIC SANDBOX</span><span className="live">● LIVE</span></div><p className="eyebrow">MARKETING DECISION QUEUE</p><h1>What should Convex do next,<br/>and why?</h1><p className="sub">One shared case per team. Signals become a clear human decision—not automatic outreach.</p></header><section className="metrics"><div><b>{open.length}</b><span>Open decisions</span></div><div><b>{open.filter(r=>r.route==="emerging").length}</b><span>Worth watching</span></div><div><b>{open.filter(r=>r.route!=="emerging").length}</b><span>Act now</span></div></section><section className="queue"><div className="queue-head"><div><p className="eyebrow">YOUR QUEUE</p><h2>Signal review</h2></div><span className="hint">Click a team to see evidence</span></div>{rows === undefined ? <div className="loading">Loading the live queue…</div> : <div className="table"><div className="table-row table-label"><span>TEAM</span><span>WHY NOW</span><span>RECOMMENDED RESPONSE</span><span>OWNER</span><span>STATE</span></div>{rows.map(row=><article className="table-row" key={row._id}><span><strong>{row.teamDisplayName}</strong><small>{label(row.route)}</small></span><span><i className={`dot ${tone(row.route)}`}/>{row.route === "emerging" ? "Production use and team adoption are holding." : row.route === "pressure" ? "Sustained comparable usage pressure." : "A team request needs a technical response."}</span><span><b>{row.recommendation}</b></span><span>{row.ownerId?.replace("user:","") ?? "Unassigned"}</span><span className={`state ${row.status ?? "open"}`}>{row.status ?? "open"}</span>{(row.status ?? "open") === "open" && <div className="actions"><button onClick={()=>decide({candidateId:row._id as any,actorId:"user:demo-owner",decision:"not_now",reason:"Synthetic UI decision"})}>Not now</button><button className="primary" onClick={()=>decide({candidateId:row._id as any,actorId:"user:demo-owner",decision:"suppress",reason:"Synthetic UI decision"})}>Suppress</button></div>}</article>)}</div>}</section></main>;
}
